In [57]:
import numpy as np
a = np.random.randint(1,20,(3,3))
b = np.random.randint(1,20,(3,2))

print(a)
print(b)



[[ 4  8 16]
 [19  3  4]
 [15 13  6]]
[[15 14]
 [19 17]
 [ 7  8]]


In [61]:
print(a)
c = a[:2,1]<10
print()

[[ 4  8 16]
 [19  3  4]
 [15 13  6]]
[ True  True]


In [85]:
import numpy as np
arr = np.array( [[21, 20, 19, 18, 17],
                 [16, 15, 14, 13, 12],
                 [11, 10,  9,  8,  7],
                 [ 6,  5,  4,  3,  2]], dtype = int)

trans = np.transpose(arr)
print(trans)
c = np.sort(trans)
print(c)
fnl = np.transpose(c)
print(fnl)

[[21 16 11  6]
 [20 15 10  5]
 [19 14  9  4]
 [18 13  8  3]
 [17 12  7  2]]
[[ 6 11 16 21]
 [ 5 10 15 20]
 [ 4  9 14 19]
 [ 3  8 13 18]
 [ 2  7 12 17]]
[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [202]:
import numpy as np 
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(4,1))
print(a)
print(b)

[[9 2 9]
 [5 6 2]
 [9 2 8]]
[[5]
 [6]
 [3]
 [2]]


In [95]:
c = np.random.randint(1,10,(3,))
print(c)

[4 5 2]


In [167]:
x = a + b
y = a + c
z = b + c
print(x)
print()
print(y)
print()
print(z)

[[ 9  5 11]
 [14  7  6]
 [14 17 16]]

[[11  8 11]
 [13  7  3]
 [10 14 10]]

[[ 6  7  4]
 [ 9 10  7]
 [12 13 10]]


In [207]:
print(b)
h = np.resize(b,(2,5))
print(h)

[[5]
 [6]
 [3]
 [2]]
[[5 6 3 2 5]
 [6 3 2 5 6]]


In [9]:
import numpy as np
a = np.random.randint(1,10,(3,2,5))
print(a)
print() 



[[[6 6 8 7 5]
  [6 6 3 4 9]]

 [[4 6 1 7 8]
  [2 1 8 1 5]]

 [[9 9 3 5 2]
  [3 7 1 2 8]]]

